// client/packages/adp-chat-component-example/vue-init-example/src/pages/full/App.vue
<script setup lang="ts">
import { useChat } from '../../shared/useChat'
import '../../shared/styles.css'

const { isOpen, openChat } = useChat({
  getConfig: () => ({
    modelType: 'full',
    logoTitle: 'ADP Chat - Full Mode',
    showFullscreenButton: false,
  }),
})
</script>

<template>
  <div class="page-container bg-plain">
    <div v-if="!isOpen" class="control-panel">
      <h2>Full Mode Demo</h2>
      <p>Chat panel is closed</p>
      <div class="control-buttons">
        <button class="control-btn" @click="openChat">Open Chat</button>
      </div>
    </div>
    <div id="chat-container"></div>
  </div>
</template>

// client/packages/adp-chat-component-example/react-init-example/src/pages/full/App.tsx
import React from 'react'
import { useChat } from '../../shared/useChat'
import '../../shared/styles.css'

const App: React.FC = () => {
  const { isOpen, openChat } = useChat({
    getConfig: () => ({
      modelType: 'full',
      logoTitle: 'ADP Chat - Full Mode',
      showFullscreenButton: false,
    }),
  })

  return (
    <div className="page-container bg-plain">
      {!isOpen && (
        <div className="control-panel">
          <h2>Full Mode Demo</h2>
          <p>Chat panel is closed</p>
          <div className="control-buttons">
            <button className="control-btn" onClick={openChat}>Open Chat</button>
          </div>
        </div>
      )}
      <div id="chat-container"></div>
    </div>
  )
}

export default App
